site_name: Python Project Template
site_description: A modern Python project template with best practices
site_author: Your Name
site_url: https://your-username.github.io/python-template

repo_name: your-username/python-template
repo_url: https://github.com/your-username/python-template

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.path
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - toc.integrate
    - toc.follow
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            heading_level: 2
            filters: ["!^_"]
            members_order: source
            docstring_style: google
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "pymdownx.superfences.fence_code_format"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: "material.extensions.emoji.twemoji"
      emoji_generator: "material.extensions.emoji.to_svg"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - abbr
